### ISSUE TITLE
Crash on block update

### ISSUE THREAD

**Issue by Bysokar** [MrTJP/MrTJPCore#23]
Not sure if you're still supporting your latest 1.7.10... but..

```
java.lang.NullPointerException: Exception in server tick loop
        at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:80)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_479_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by covers1624** [comment]
1.7 isn't supported anymore, nor was it when this was opened.
