### ISSUE TITLE
[1.10.2] Crash (NullPointerException) when opening non-empty ProjectRed backpack 

### ISSUE THREAD

**Issue by Tommsy64** [MrTJP/MrTJPCore#29]
When I try opening a ProjectRed backpack that contains at least one item, my game crashes:

```
java.lang.NullPointerException: Unexpected error
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.GenSeqLike$class.isDefinedAt(GenSeqLike.scala:72)
	at scala.collection.mutable.ArrayOps$ofRef.isDefinedAt(ArrayOps.scala:186)
	at mrtjp.core.inventory.TInventory$$anonfun$loadInv$1.apply$mcVI$sp(invtraits.scala:89)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at mrtjp.core.inventory.TInventory$class.loadInv(invtraits.scala:84)
	at mrtjp.projectred.exploration.BagInventory.loadInv(items.scala:114)
	at mrtjp.core.inventory.TInventory$class.loadInv(invtraits.scala:80)
	at mrtjp.projectred.exploration.BagInventory.loadInv(items.scala:114)
	at mrtjp.projectred.exploration.BagInventory.loadInventory(items.scala:125)
	at mrtjp.projectred.exploration.BagInventory.<init>(items.scala:116)
	at mrtjp.projectred.exploration.ItemBackpack$.createContainer(items.scala:77)
	at mrtjp.projectred.exploration.ItemBackpack.openGui(items.scala:54)
	at mrtjp.projectred.exploration.ItemBackpack.func_180614_a(items.scala:42)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:146)
        ...
```

Core version: `MrTJPCore-1.10.2-2.0.1.20`
ProjectRed version: `ProjectRed-1.10.2-4.8.4.49`

* Crash report in my modpack: [pastebin](https://pastebin.com/ULZHpVjY)
* Crash with only MrTJPCore + ProjectRed: [pastebin](https://pastebin.com/er4PhRgS)

**Comment by MrTJP** [comment]
Update.
